#!/bin/sh

export LD_LIBRARY_PATH=..

for x in *.c
do
    cc -I .. $x -L .. -lmcpack
    ./a.out

    if [ $? -eq 0 ]
    then
        echo "[OK]       $x"  
    else
        echo "^^^ [FAIL] $x"  
    fi

    rm a.out
done
