#!/bin/sh

for x in *.c
do
    cc -I.. ../obsidian_serialize.a $x
    ./a.out

    if [ $? -eq 0 ]
    then
        echo "[OK]       $x"  
    else
        echo "^^^ [FAIL] $x"  
    fi

    rm a.out
done
